apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zhzv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-zhzv@sha256:5de45b99d2ccbbcb205b8d323a8ad677d4b698d68d2dcf576c43ac0c77e8e703
        name: my-nodejs
        resources: {}
status: {}
